#!/usr/bin/env bash

source klibs

current="$(kubectl config current-context)"

kns() {
  local namespace
  local selected

  check_dependencies "kubectl awk fzf"

  namespace="$(kubectl config get-contexts "$current" | awk "/$current/ {print \$5}")"

  if [[ -z "$namespace" ]]; then
    namespace="default"
  fi

  selected=$( (kubectl get namespaces -o name | sed "s-namespaces/--" ) | fzf -0 -1 --tac --prompt "Current Namespace $namespace> ")

  if [[ ! -z "$selected" ]]; then
      set_namespace $selected
  fi
}

set_namespace(){
    local selected_namespace
    selected_namespace=$1
    kubectl config set-context "$current" "--namespace=${selected_namespace##namespace/}"
    printf "Set \"$selected_namespace\"."
}

if [ -z "$1" ]; then
    kns
else
    set_namespace $1
fi
