#!/usr/bin/env bash

source klibs

switch_cluster() {
  local current
  local cluster
  local selected

  check_dependencies "fzf kubectl awk"

  current="$(kubectl config current-context)"
  cluster="$(kubectl config get-contexts "$current" | awk "/$current/ {print \$2}")"
  selected=$(kubectl config get-contexts -o name | fzf -0 -1 --tac --prompt "Current cluster: $current> ")

  if [[ ! -z "$selected" ]]; then
      set_cluster $selected
  fi
}

set_cluster(){
    local selected_cluster
    selected_cluster=$1
    kubectl config use-context "$selected_cluster"
    echo "Set Cluster Context to \"$selected_cluster\"."
}

if [ -z "$1" ]; then
    switch_cluster
else
    set_cluster $1
fi
